name: CI-build

on:
  # on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: Gr1N/setup-poetry@v7

      - name: Create env and install package
        run: |
          poetry install
          poetry build
          pip3 install "dist/$(ls -t dist | head -1)"

      - name: Trigger linting workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TIDYCSV_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: successful-build-1
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
