# This is a basic workflow to help you get started with Actions

name: CI-build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # use poetry on github actions :
      - uses: Gr1N/setup-poetry@v7

      - name: Create env and install package
        run: |
          poetry install
          poetry build
          pip3 install "dist/$(ls -t dist | head -1)"

      - name: Trigger linting workflow
        if: success()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TIDYCSV_GHA_PAT }}
          repository: ${{ github.repository }}
          event-type: successful-build-1
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'