name: mypy

on:
  repository_dispatch:
    types: [successful-build-1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - uses: Gr1N/setup-poetry@v7

      # Runs a set of commands using the runners shell
      - name: Setup
        run: poetry install

      - name: Run mypy to check types
        run: |
          poetry run mypy tidycsv
