name: tests

on:
  repository_dispatch:
    types: [successful-build-1]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# jobs can run sequentially or in parallel
jobs:
  tests:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}
      - uses: Gr1N/setup-poetry@v7
      - uses: actions/setup-go@v2

      - name: Install goodls and download data
        env:
          GOODLS_APIKEY: ${{ secrets.GDRIVE_API_KEY }}
          REPO_URL: ${{ secrets.GDRIVE_REPO_URL }}
        run: |
          #[[ ! -z "$GOODLS_APIKEY" ]] && echo "Not empty" || command_not_found
          #[[ ! -z "$REPO_URL" ]] && echo "Not empty" || command_not_found
          go get -u github.com/tanaikech/goodls
          export GOODLS_BIN=$(go env GOPATH)/bin/goodls
          #echo $REPO_URL > .repo_url.txt
          #$GOODLS_BIN < .repo_url.txt
          #rm .repo_url.txt
          echo $REPO_URL | $GOODLS_BIN
          mv raw data
          echo " "
          ls
